# NOTE THIS IS BUSTED UNTIL: 
#  1. don't need to wait on admin, or wait on blue admin
#  2. pf-engine can deploy cluster service. 
# helm upgrade --install green pingidentity/devops -f /Users/samirgandhi/projects/devops/samir-server-profiles/examples/multi-dns-ping/green-values.yaml
debug:
  values: true
global:
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
  addReleaseNameToResource: prepend
  ingress:
    addReleaseNameToHost: prepend
    annotations:
      kubernetes.io/ingress.class: nginx-public
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    defaultDomain: ping-devops.com
    defaultTlsSecret: null
    enabled: true
# pingfederate-admin:
#   chartEnabled: true
#   envs:
#     CLUSTER_BIND_ADDRESS: NON_LOOPBACK
#     CLUSTER_NAME: tmp-pf
#     DNS_QUERY_LOCATION: "green-pingfederate-cluster.tmp-pdog.svc.cluster.local,blue-pingfederate-cluster.ping-devops.com"
#     DNS_RECORD_TYPE: A
#     OPERATIONAL_MODE: CLUSTERED_CONSOLE
#     PING_IDENTITY_ACCEPT_EULA: "YES"
#     SERVER_PROFILE_PATH: getting-started/pingfederate
#     SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
#   image:
#     name: pingfederate
#     pullPolicy: Always
#     repository: 574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds
#     tag: latest
#   services:
#     clusterExternalDNSHostname: green-pingfederate-cluster.ping-devops.com

pingfederate-engine:
  chartEnabled: true
  clustering:
    autoscaling:
      enabled: false
  container:
    replicaCount: 2
  envs:
    CLUSTER_BIND_ADDRESS: NON_LOOPBACK
    CLUSTER_NAME: tmp-pf
    DNS_QUERY_LOCATION: "green-pingfederate-cluster.tmp-pdog.svc.cluster.local,blue-pingfederate-cluster.ping-devops.com"
    DNS_RECORD_TYPE: A
    OPERATIONAL_MODE: CLUSTERED_ENGINE
    PING_IDENTITY_ACCEPT_EULA: "YES"
    SERVER_PROFILE_PATH: getting-started/pingfederate
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  image:
    name: pingfederate
    pullPolicy: Always
    repository: 574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds
    tag: latest
  services:
    clusterExternalDNSHostname: green-pingfederate-cluster.ping-devops.com
