apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingdatagovernance
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    role: pingdatagovernance
  name: pingdatagovernance-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ldaps
    port: 636
  selector:
    role: pingdatagovernance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdatagovernance
  template:
    metadata:
      labels:
        role: pingdatagovernance
      name: pingdatagovernance
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingdatagovernance-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingdatagovernance:edge
        name: pingdatagovernance
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 636
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
---            
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdataconsole
  name: pingdataconsole
spec:
  ports:
  - name: https
    port: 8443
  selector:
    role: pingdataconsole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdataconsole
  name: pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdataconsole
  template:
    metadata:
      labels:
        role: pingdataconsole
      name: pingdataconsole
    spec:
      containers:
      - image: pingidentity/pingdataconsole:edge
        name: pingdataconsole
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
---
apiVersion: v1
data:
  HTTPS_PORT: "8443"
  PING_EXTERNAL_BASE_URL: localhost
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: pdg-pap-integration/pingdatagovernancepap
  SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    role: pingdatagovernancepap
  name: pingdatagovernancepap-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdatagovernancepap
  name: pingdatagovernancepap
spec:
  ports:
  - name: https
    port: 8443
  selector:
    role: pingdatagovernancepap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdatagovernancepap
  name: pingdatagovernancepap
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdatagovernancepap
  template:
    metadata:
      labels:
        role: pingdatagovernancepap
      name: pingdatagovernancepap
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingdatagovernancepap-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingdatagovernancepap:edge
        name: pingdatagovernancepap
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
